backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "parts"
    label: "Auto Parts"
    folder: "parts"
    create: true
    fields:
      - {label: "Part Name", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
